project:
  type: website
  output-dir: docs

website:
  title: "Numerical Methods Notes"
  reader-mode: true
  sidebar:
    style: "docked"
    search: true
    contents: auto


format:
  html:
    # theme: sketchy
    # theme: lux
    # theme: sandstone
    theme: litera
    css: styles.css
    toc: true



